config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'posts' => 'posts#index'
    post 'posts' => 'posts#create'
    get 'rooms/:id' => 'rooms#show'
  end

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#delete', as: :logout
  get 'users/new' => 'users#new', as: :register
  post 'users' => 'users#create', as: :users
  get 'user/:id' => 'users#show', as: :user
  root 'rooms#index'
  get 'rooms/new' => 'rooms#new', as: :new_room
  post 'rooms' => 'rooms#create', as: :rooms
  get 'rooms/:id' => 'rooms#show', as: :room

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  belongs_to :room

  validates :text, presence: true

end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :users
  has_many :posts

  validates :room_name, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts

  has_secure_password

  validates :username, :password, presence: true
  attachment :photo

end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  before_action do
    if @current_user.nil?
      # redirect_to sign_in_path
      render json: {authenticated: false}, status: 401
    end
  end

  def index
     @posts = Post.order("created_at desc")
  end

  def create
    @post = Post.new params.require(:post).permit(:text)
    @post.user = @current_user
    @post.room = Room.find_by(params[:id])
     if @post.save
      render :show
    else
      render json: {errors: @post.errors}, status: 422
    end
  end
end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < ApplicationController

  skip_before_filter :verify_authenticity_token

  before_action do
    if @current_user.nil?
      # redirect_to sign_in_path
      render json: {authenticated: false}, status: 401
    end
  end

  def show
     @room = Room.find_by id: params[:id]
     @posts = @room.posts
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to login_path
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
    # @post = Post.new
  end

  def create
    # @post = Post.new
    # @post.text = params[:post][:text]
    # @post.user = @current_user
    # if @post.save
    #   redirect_to posts_path
    # else
    #   render :new
    # end
  end

  def delete
  #   @post = Post.find_by id: params[:id]
  #   @post.destroy
  #   redirect_to posts_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  before_action do
    @current_user = User.find_by id: session[:user_id]
    if @current_user.blank?
      redirect_to login_path
    end
  end

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find_by id: params[:id]
    @posts = @room.posts
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new
    @room.room_name = params[:room][:room_name]
    # @room.posts.get_room_id
    # @room.user = @current_user
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit( :username, :password, :photo)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slack</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="nav_bar">
    <div class="slack_icon">
      <%= link_to root_path, class: "button" do %>
        <%= image_tag "Slack_Icon.png", style:"max-height: 100%;" %>
      <% end %>
    </div>
    <div class="session_icon">
      <% if @current_user %>
          <%= link_to logout_path, class: "button" do %>
            <h1>Logout</h1>
          <% end %>
        <% else %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/delete.html.erb
<h1>Rooms#delete</h1>
<p>Find me in app/views/rooms/delete.html.erb</p>

app/views/rooms/index.html.erb
<h1><%= @rooms.length %> active rooms</h1>

<div class="room_icon">
  <% if @current_user %>
      <%= link_to "Create Room", new_room_path, class: "button" %>
    <% else %>
  <% end %>
</div>

<% @rooms.each do |room| %>
  <h1><%= link_to room.room_name, room_path(id: room.id) %></h1>
<% end %>

app/views/rooms/new.html.erb
<div class="room_container">

    <h1>Create a Room</h1>

    <% if @room.errors.any? %>
      <%= pluralize(@room.errors.count, 'error') %> need your attention.
      <ul class="mdl-list">
        <% @room.errors.full_messages.each do |msg| %>
          <li class="mdl-list__item"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @room do |f| %>
      <div class="">
        <%= f.label :room_name %>
        <%= f.text_field :room_name %>
      </div>

      <div class="">
        <%= f.submit class: "btn btn-success", value: "Create Room" %>

      </div>
    <% end %>

</div>

app/views/rooms/show.html.erb
<h1>Welcome to <b><%= @room.room_name %></b>, <%= @current_user.username %>.</h1>

<%= react_component 'Form' %>
<%= react_component 'PostList' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="registration_container">

    <h1>Register Here</h1>

    <% if @user.errors.any? %>
      <%= pluralize(@user.errors.count, 'error') %> need your attention.
      <ul class="mdl-list">
        <% @user.errors.full_messages.each do |msg| %>
          <li class="mdl-list__item"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @user do |f| %>
      <div class="">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>

      <div class="">
        <%= f.label :password %>
        <%= f.text_field :password %>
      </div>

      <div class="">
        <%= f.label :photo %>
        <%= f.attachment_field :photo %>
      </div>

      <div class="">
        <%= f.submit class: "btn btn-success", value: "Register User" %>

      </div>
    <% end %>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
Welcome#Index